name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
      # Build
      - run: npm ci
      - run: npm run check
      - run: npm run build
      # Deploy
      - uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: "gpt-tg-bot-deploy-bucket"
          folder-id: "b1g3gioifpa83u7ajerc"
          function-name: "gpt-tg-bot"
          runtime: "nodejs16"
          memory: "256Mb"
          execution-timeout: "60"
          entrypoint: "dist/index.handler"
          environment: |
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_BOT_SUPPORTED_CHAT_IDS=${{ secrets.TELEGRAM_BOT_SUPPORTED_CHAT_IDS }}
            OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}
            OPEN_AI_SYSTEM_MESSAGE=${{ secrets.OPEN_AI_SYSTEM_MESSAGE }}
          include: |
            ./dist
            package.json
            package-lock.json
            ffmpeg
          exclude: |
            ./dist/dev.js
