name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            # Build
            - run: npm ci
            - run: npm run build
            - run: cp package.json build/package.json
            - run: cp package-lock.json build/package-lock.json
            # Deploy
            - uses: goodsmileduck/yandex-serverless-action@v2
              with:
                  token: ${{ secrets.YC_OAUTH_TOKEN }}
                  function_id: ${{ env.YC_CLOUD_FUNCTION_ID }}
                  runtime: "nodejs16"
                  entrypoint: "index.handler"
                  environment: TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}
                  memory: "128"
                  source: "./dist"
                  execution_timeout: "60"
